# Generated by Django 6.1 on 2026-09-19 21:50

import django.db.models.deletion
import imaging.models
import imaging.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready for Training'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imaging_dataset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imaging.models.dataset_image_upload_path, validators=[imaging.validators.validate_image_file])),
                ('class_label', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imaging.dataset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_dataset_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imaging_dataset_image',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'class_label'], name='imaging_dat_dataset_236618_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imaging.models.uploaded_image_upload_path, validators=[imaging.validators.validate_image_file])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imaging_uploaded_image',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='imaging_upl_user_id_ad538c_idx')],
            },
        ),
    ]
