# Generated by Django 6.1 on 2026-09-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('IMAGE_UPLOADED', 'Image Uploaded'), ('PREDICTION_CREATED', 'Prediction Created'), ('TRAINING_STARTED', 'Training Started'), ('TRAINING_COMPLETED', 'Training Completed'), ('TRAINING_FAILED', 'Training Failed'), ('MODEL_UPDATED', 'Model Updated')], db_index=True, max_length=32)),
                ('actor_identifier', models.CharField(blank=True, max_length=254)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reference_model', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='audit_log_event_t_ae55c9_idx'), models.Index(fields=['user', '-created_at'], name='audit_log_user_id_b57afc_idx')],
            },
        ),
    ]
